//SOURCES ChatFunction.java

import dev.langchain4j.model.chat.response.ChatResponse;
import dev.langchain4j.service.TokenStream;

import java.util.List;
import java.util.concurrent.CompletableFuture;

/// Utility class for running chatbot demos with interactive question selection and streaming response display.
public class ChatbotUtils {

  static int totalTokensUsed = 0;

  /// System prompts for different chatbot demos. Each entry is a unique prompt that can be used to set up the chatbot's behavior and knowledge.
  final static String SYSTEM_PROMPT_DEVOXX_FRANCE_EXPERT = """
        Tu es un expert de la conférence Devoxx France.

        Devoxx France propose plusieurs formats de sessions :
         - Keynotes
         - Deep Dive (2h ou 3h)
         - Hands-on Lab (2h ou 3h)
         - BOF (Birds of a Feather)
         - Conference (45 min)
         - Lunch Talk (15 min)
         - Tools-in-Action (30 min)

        Utilise les données en ta possession concernant DEVOXX FRANCE et non les autres Devoxx.
        Indique pour quel Devoxx tu réponds (ex: Devoxx France 2026) dans ta réponse.
        Si tu ne connais pas la réponse, n'essaye pas de l'inventer, indique clairement que tu ne sais pas.
        """;

  /// Available questions for all chatbot demos.
  /// Each entry is a unique question text that can be used with any script.
  enum QUESTIONS {
    WHERE_IS_DEVOXX("Où se déroule Devoxx ?"),
    HOW_MANY_TALKS("Combien il y a-t-il de talks à Devoxx France ?"),
    AI_ADD_KNOWLEDGE("Il y a t il un talk sur l'IA à Devoxx France qui indique comment rajouter de la connaissance à mon modèle ?"),
    WHEN_IS_DEVOXX("A quelle date se déroule Devoxx France ?"),
    MAKE_AGENDA("Je suis intéressé par les talks sur l'IA et Java, propose moi un agenda."),
    TALKS_ON_AI("Quels sont les talks sur l'IA à Devoxx France 2026 ?"),
    WEDNESDAY_AGENDA("Quel est le programme du mercredi à Devoxx France ?"),
    SPEAKER_TALKS("Quels sont les talks de Stéphane Philippart à Devoxx France 2026 ?"),
    TALKS_TODAY("Donne moi la date du jour et quels sont les talks aujourd'hui ?"),
    TALKS_TOMORROW("Quels sont les talks demain ?"),
    TALKS_AT_1_30_PM("Quels sont les hands on lab qui commencent aujourd'hui à 13h30 ?");

    public final String question;

    QUESTIONS(String question) {
      this.question = question;
    }

    @Override
    public String toString() {
      return question;
    }
  }

  /// Displays an interactive menu of available questions and loops until the user
  /// exits by pressing Enter without a number. Each iteration asks a question and
  /// displays the streaming response.
  ///
  /// @param assistant the chat function to call for the selected question
  /// @param available the questions to display in the menu;
  ///                  if none are passed, all QUESTIONS values are shown
  static void runInteractive(ChatFunction assistant, QUESTIONS... available) {
    var menu = available.length > 0 ? List.of(available) : List.of(QUESTIONS.values());

    while (true) {
      IO.println("\n🎯  Questions disponibles :\n");
      for (int i = 0; i < menu.size(); i++) {
        IO.println("  %2d. %s".formatted(i + 1, menu.get(i).question));
      }

      IO.print("\n👉  Votre choix (Entrée pour quitter) : ");
      var input = System.console().readLine().trim();

      if (input.isEmpty()) {
        IO.println("Au revoir !");
        break;
      }

      var selected = menu.get(Integer.parseInt(input) - 1);
      IO.println("");

      IO.println("💬 : %s".formatted(selected.toString()));
      displayChatbotResponse(assistant.chat(selected.toString()));
      IO.readln("\nAppuyez sur une touche pour continuer...");
    }
  }

  /// This method displays the chatbot response in the console as it is being generated, and also counts the total tokens used for the response.
  /// It takes the user message and the TokenStream as parameters.
  ///
  /// @param tokenStream the stream of tokens generated by the chatbot in response to the user message
  static void displayChatbotResponse(TokenStream tokenStream) {
    CompletableFuture<ChatResponse> futureChatResponse = new CompletableFuture<>();


    IO.println("🤖 : ");
    tokenStream
        .onPartialResponse(IO::print)
        //.onPartialThinking(IO::println)
        //.onRetrieved(IO::println)
        //.onIntermediateResponse(IO::print)
        // This will be invoked right before a tool is executed. BeforeToolExecution contains ToolExecutionRequest (e.g. tool name, tool arguments, etc.)
//        .beforeToolExecution(toolExecutionRequest -> {
//          IO.println("⚠️ Êtes-vous sûr de vouloir exécuter l'outil %s ? ⚠️".formatted(toolExecutionRequest.request().name()));
//          var answer = IO.readln();
//          if (!"ok".equalsIgnoreCase(answer)) {
//            throw new RuntimeException("🛑 Outil non validé !! 🛑");
//          } else {
//            IO.println("✅  Outil validé. ✅");
//          }
//        })
        // This will be invoked right after a tool is executed. ToolExecution contains ToolExecutionRequest and tool execution result.
        //.onToolExecuted(IO::println)
        .onCompleteResponse(response -> {
          var inputTokenCount = response.tokenUsage()
              .inputTokenCount();
          var outputTokenCount = response.tokenUsage()
              .outputTokenCount();
          IO.println("%n%n⬆️  Input tokens count: %s".formatted(inputTokenCount));
          IO.println("⬇️  Output tokens count: %s".formatted(outputTokenCount));
          totalTokensUsed += inputTokenCount + outputTokenCount;
          futureChatResponse.complete(response);
        })
        .onError(Throwable::printStackTrace)
        .start();

    futureChatResponse.join();
    IO.println("\n");
  }
}
